#ifndef PROJECT_CONFIG_H
#define PROJECT_CONFIG_H

/**
 * @file project_config.h
 * @brief 舵轮步兵云台板项目配置。
 * @note 本仓库固定生成云台板固件；与底盘仓库保持相同的板间协议参数。
 */

#include "app_config.h"
#include "board_config.h"

/* 可选功能。视觉只存在于云台板；裁判系统当前不接入。 */
#if APP_BOARD_ROLE == APP_BOARD_ROLE_GIMBAL
#define PROJECT_HAS_VISION_USB
#endif

/* 设备安装位置：修改后两块板必须使用相同配置。 */
#define PROJECT_DR16_LOCATION APP_DEVICE_LOCATION_CHASSIS
#define PROJECT_FEEDER_LOCATION APP_DEVICE_LOCATION_GIMBAL

#undef APP_DR16_LOCATION
#define APP_DR16_LOCATION PROJECT_DR16_LOCATION
#undef APP_FEEDER_LOCATION
#define APP_FEEDER_LOCATION PROJECT_FEEDER_LOCATION

/* 物理 CAN 分配。 */
#define PROJECT_CAN_GIMBAL_PITCH BOARD_CONFIG_CAN_1
#define PROJECT_CAN_GIMBAL_YAW BOARD_CONFIG_CAN_2
#define PROJECT_CAN_BOARD_LINK BOARD_CONFIG_CAN_2
#define PROJECT_CAN_CHASSIS_DRIVE BOARD_CONFIG_CAN_1
#define PROJECT_CAN_CHASSIS_STEERING BOARD_CONFIG_CAN_3
#define PROJECT_CAN_SHOOTER BOARD_CONFIG_CAN_1

/* 板间通信使用成对的收发 ID 段，方向与参考英雄双板工程一致。 */
#define PROJECT_GIMBAL_COMM_TX_BASE_ID (0x500U)
#define PROJECT_CHASSIS_COMM_TX_BASE_ID (0x510U)
#if APP_BOARD_ROLE == APP_BOARD_ROLE_GIMBAL
#define PROJECT_BOARD_COMM_TX_BASE_ID PROJECT_GIMBAL_COMM_TX_BASE_ID
#define PROJECT_BOARD_COMM_RX_BASE_ID PROJECT_CHASSIS_COMM_TX_BASE_ID
#else
#define PROJECT_BOARD_COMM_TX_BASE_ID PROJECT_CHASSIS_COMM_TX_BASE_ID
#define PROJECT_BOARD_COMM_RX_BASE_ID PROJECT_GIMBAL_COMM_TX_BASE_ID
#endif
#define PROJECT_BOARD_COMM_TX_TIMEOUT_MS (2U)
#define PROJECT_BOARD_COMM_OFFLINE_MS (100U)

/* 云台：Pitch DM4310 / CAN1，Yaw GM6020 / CAN2。 */
#define PROJECT_PITCH_DM4310_COMMAND_ID (0x01U)
#define PROJECT_PITCH_DM4310_FEEDBACK_ID (0x11U)
#define PROJECT_YAW_GM6020_ID (1U)
#define PROJECT_YAW_GM6020_ENCODER_ZERO (0U)

/* 底盘：四个 M3508 / CAN1，四个 GM6020 / CAN3。 */
#define PROJECT_CHASSIS_MODULE_COUNT (4U)
#define PROJECT_DRIVE_FRONT_LEFT_ID (1U)
#define PROJECT_DRIVE_FRONT_RIGHT_ID (2U)
#define PROJECT_DRIVE_REAR_LEFT_ID (3U)
#define PROJECT_DRIVE_REAR_RIGHT_ID (4U)
#define PROJECT_STEERING_FRONT_LEFT_ID (1U)
#define PROJECT_STEERING_FRONT_RIGHT_ID (2U)
#define PROJECT_STEERING_REAR_LEFT_ID (3U)
#define PROJECT_STEERING_REAR_RIGHT_ID (4U)

/* 发射：两摩擦轮固定在云台板，拨弹盘位置由 PROJECT_FEEDER_LOCATION 选择。 */
#define PROJECT_FRICTION_LEFT_ID (5U)
#define PROJECT_FRICTION_RIGHT_ID (6U)
#define PROJECT_FEEDER_ID (7U)

/* 电机公共参数。零位和方向必须按实车标定后修改。 */
#define PROJECT_MOTOR_FEEDBACK_TIMEOUT_MS (50U)
#define PROJECT_DJI_CURRENT_SCALE_A_PER_COUNT (0.00061035F)
#define PROJECT_DJI_MAXIMUM_TEMPERATURE_C (80.0F)
#define PROJECT_MOTOR_DIRECTION_FORWARD (1.0F)
#define PROJECT_MOTOR_DIRECTION_REVERSE (-1.0F)

/* 舵轮几何。当前值是安全占位，不代表实车尺寸。 */
#define PROJECT_CHASSIS_HALF_WHEELBASE_M (0.25F)
#define PROJECT_CHASSIS_HALF_TRACK_M (0.25F)
#define PROJECT_CHASSIS_WHEEL_RADIUS_M (0.076F)
#define PROJECT_CHASSIS_DRIVE_REDUCTION_RATIO (19.2032F)
#define PROJECT_CHASSIS_MAX_WHEEL_VELOCITY_M_PER_S (4.0F)

/* 云台范围。 */
#define PROJECT_GIMBAL_PITCH_MIN_RAD (-0.50F)
#define PROJECT_GIMBAL_PITCH_MAX_RAD (0.45F)
#define PROJECT_GIMBAL_TARGET_TOLERANCE_RAD (0.01F)

/* PID 初值仅用于建立可运行框架，上车前必须通过 Ozone 调整。 */
#define PROJECT_PID_DERIVATIVE_FILTER_HZ (50.0F)
#define PROJECT_PID_INTEGRAL_LIMIT (5.0F)
#define PROJECT_PID_CURRENT_OUTPUT_LIMIT_A (8.0F)
#define PROJECT_DRIVE_VELOCITY_OUTPUT_LIMIT_A (10.0F)
#define PROJECT_POSITION_VELOCITY_LIMIT_RAD_PER_S (20.0F)

#define PROJECT_DRIVE_VELOCITY_KP (0.5F)
#define PROJECT_DRIVE_VELOCITY_KI (0.0F)
#define PROJECT_DRIVE_VELOCITY_KD (0.0F)
#define PROJECT_STEERING_POSITION_KP (8.0F)
#define PROJECT_STEERING_POSITION_KI (0.0F)
#define PROJECT_STEERING_POSITION_KD (0.0F)
#define PROJECT_STEERING_VELOCITY_KP (0.5F)
#define PROJECT_STEERING_VELOCITY_KI (0.0F)
#define PROJECT_STEERING_VELOCITY_KD (0.0F)
#define PROJECT_YAW_POSITION_KP (8.0F)
#define PROJECT_YAW_POSITION_KI (0.0F)
#define PROJECT_YAW_POSITION_KD (0.0F)
#define PROJECT_YAW_VELOCITY_KP (0.5F)
#define PROJECT_YAW_VELOCITY_KI (0.0F)
#define PROJECT_YAW_VELOCITY_KD (0.0F)

/* 安全与遥控。 */
#define PROJECT_DR16_OFFLINE_TIMEOUT_MS (100U)
#define PROJECT_SAFETY_DISCONNECTION_MS (500U)

#if (PROJECT_DR16_LOCATION != APP_DEVICE_LOCATION_GIMBAL) &&                              \
    (PROJECT_DR16_LOCATION != APP_DEVICE_LOCATION_CHASSIS)
#error "PROJECT_DR16_LOCATION must select the gimbal or chassis board"
#endif

#if (PROJECT_FEEDER_LOCATION != APP_DEVICE_LOCATION_GIMBAL) &&                            \
    (PROJECT_FEEDER_LOCATION != APP_DEVICE_LOCATION_CHASSIS)
#error "PROJECT_FEEDER_LOCATION must select the gimbal or chassis board"
#endif

#if (PROJECT_GIMBAL_COMM_TX_BASE_ID <= 0x20FU) ||                                  \
    (PROJECT_CHASSIS_COMM_TX_BASE_ID <= 0x20FU)
#error "Board communication identifiers must not overlap DJI motor identifiers"
#endif

#endif
